<?php

namespace Database\Seeders;

use App\Models\Configuration\Sucursal;
use Illuminate\Database\Seeder;

class SucursalSeeder extends Seeder
{
    public function run(): void
    {
        $sucursales = [
            [
                'code' => 'LIM01',
                'codeSunat' => '0001',
                'igv' => 18,
                'serieFactura' => 'F001',
                'serieBoleta' => 'B001',
                'serieGuiaRemision' => 'T001',
                'serieNotaCreditoFactura' => 'FC01',
                'serieNotaCreditoBoleta' => 'BC01',
                'serieNotaDebitoFactura' => 'FD01',
                'serieNotaDebitoBoleta' => 'BD01',
                'color' => '#3B82F6',
                'name' => 'Lima Centro',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'Cercado de Lima',
                'urbanizacion' => 'Centro',
                'address' => 'Jr. Lampa 123',
                'phone' => '01-1234567',
                'email' => 'lima@transportes.com',
                'ubigeo' => '150101',
                'isActive' => true,
            ],
            [
                'code' => 'LIM02',
                'codeSunat' => '0002',
                'igv' => 18,
                'serieFactura' => 'F002',
                'serieBoleta' => 'B002',
                'serieGuiaRemision' => 'T002',
                'serieNotaCreditoFactura' => 'FC02',
                'serieNotaCreditoBoleta' => 'BC02',
                'serieNotaDebitoFactura' => 'FD02',
                'serieNotaDebitoBoleta' => 'BD02',
                'color' => '#10B981',
                'name' => 'Lima Norte',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'San Martín de Porres',
                'urbanizacion' => 'Los Olivos',
                'address' => 'Av. Carlos Izaguirre 456',
                'phone' => '01-2345678',
                'email' => 'norte@transportes.com',
                'ubigeo' => '150135',
                'isActive' => true,
            ],
            [
                'code' => 'LIM03',
                'codeSunat' => '0003',
                'igv' => 18,
                'serieFactura' => 'F003',
                'serieBoleta' => 'B003',
                'serieGuiaRemision' => 'T003',
                'serieNotaCreditoFactura' => 'FC03',
                'serieNotaCreditoBoleta' => 'BC03',
                'serieNotaDebitoFactura' => 'FD03',
                'serieNotaDebitoBoleta' => 'BD03',
                'color' => '#F59E0B',
                'name' => 'Lima Sur',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'Villa El Salvador',
                'urbanizacion' => 'Villa El Salvador',
                'address' => 'Av. Pachacútec 789',
                'phone' => '01-3456789',
                'email' => 'sur@transportes.com',
                'ubigeo' => '150142',
                'isActive' => true,
            ],
            [
                'code' => 'ARE01',
                'codeSunat' => '0004',
                'igv' => 18,
                'serieFactura' => 'F004',
                'serieBoleta' => 'B004',
                'serieGuiaRemision' => 'T004',
                'serieNotaCreditoFactura' => 'FC04',
                'serieNotaCreditoBoleta' => 'BC04',
                'serieNotaDebitoFactura' => 'FD04',
                'serieNotaDebitoBoleta' => 'BD04',
                'color' => '#EF4444',
                'name' => 'Arequipa',
                'departamento' => 'Arequipa',
                'provincia' => 'Arequipa',
                'distrito' => 'Yanahuara',
                'urbanizacion' => 'Yanahuara',
                'address' => 'Av. Ejército 321',
                'phone' => '054-123456',
                'email' => 'arequipa@transportes.com',
                'ubigeo' => '040101',
                'isActive' => true,
            ],
            [
                'code' => 'TRU01',
                'codeSunat' => '0005',
                'igv' => 18,
                'serieFactura' => 'F005',
                'serieBoleta' => 'B005',
                'serieGuiaRemision' => 'T005',
                'serieNotaCreditoFactura' => 'FC05',
                'serieNotaCreditoBoleta' => 'BC05',
                'serieNotaDebitoFactura' => 'FD05',
                'serieNotaDebitoBoleta' => 'BD05',
                'color' => '#8B5CF6',
                'name' => 'Trujillo',
                'departamento' => 'La Libertad',
                'provincia' => 'Trujillo',
                'distrito' => 'Trujillo',
                'urbanizacion' => 'Centro',
                'address' => 'Jr. Pizarro 654',
                'phone' => '044-123456',
                'email' => 'trujillo@transportes.com',
                'ubigeo' => '130101',
                'isActive' => true,
            ],
        ];

        foreach ($sucursales as $sucursal) {
            Sucursal::create($sucursal);
        }
    }
}
